copy "..\..\dynamic-plugins\sf_engine\sf_snort_plugin_hdropts.c" ..\..\detection-plugins\sf_snort_plugin_hdropts.c.new
c:\cygwin\bin\sed -e "s/_ded.errMsg/ErrorMessage/g" -e "s/sf_snort_packet.h/decode.h/g" -e "s/SFSnortPacket/Packet/g" -e "s/ip4_header/iph/g" -e "s/tcp_header/tcph/g" -e "s/proto/ip_proto/g" -e "s/type_service/ip_tos/g" -e "s/time_to_live/ip_ttl/g" -e "s/num_ip_options/ip_option_count/g" -e "s/IPOptions/Options/g" -e "s/option_code/code/g" -e  "s/acknowledgement/th_ack/g" -e "s/sequence/th_seq/g" -e "s/tcph->flags/tcph->th_flags/g" -e "s/tcph->window/tcph->th_win/g" -e "s/num_tcp_options/tcp_option_count/g" -e "s/icmp_header/icmph/g" -e "s/ICMP_ECHO_REPLY/ICMP_ECHOREPLY/g" -e "s/ICMP_ECHO_REQUEST/ICMP_ECHO/g" -e "s/icmph_union.echo.id/s_icmp_id/g" -e "s/icmph_union.echo.seq/s_icmp_seq/g" ../../detection-plugins/sf_snort_plugin_hdropts.c.new > ../../detection-plugins/sf_snort_plugin_hdropts.c
c:\cygwin\bin\bison -d -psfat_ -o../../target-based/sf_attribute_table.c ../../target-based/sf_attribute_table.y
c:\cygwin\bin\flex -i -Psfat -o../../target-based/sf_attribute_table_parser.c ../../target-based/sf_attribute_table_parser.l
copy ..\..\debug.h ..\..\dynamic-plugins\sf_engine\debug.h.new
c:\cygwin\bin\sed -e "s/DebugMessageFile = /*_ded.debugMsgFile = /" -e "s/DebugMessageLine = /*_ded.debugMsgLine = /" -e "s/; DebugMessageFunc$/; _ded.debugMsg/" -e "s/; DebugWideMessageFunc$/; _ded.debugWideMsg/" ../../dynamic-plugins/sf_engine/debug.h.new > ../../dynamic-plugins/sf_engine/debug.h
copy ..\..\ipv6_port.h ..\..\dynamic-plugins\sf_engine\ipv6_port.h.new
c:\cygwin\bin\sed -e "s/->iph->ip_src/->ip4_header->source/" -e "s/->iph->ip_dst/->ip4_header->destination/" -e "s/->iph->/->ip4_header->/" -e "s/->iph$$/->ip4_header/" -e "s/orig_iph/orig_ip4_header/" -e "s/ip_verhl/version_headerlength/" -e "s/ip_tos/type_service/" -e "s/ip_len/data_length/" -e "s/ip_id/identifier/" -e "s/ip_off/offset/" -e "s/ip_ttl/time_to_live/" -e "s/ip_proto/proto/" -e "s/ip_csum/checksum/" -e "s/p->iph$/p->ip4_header/" ../../dynamic-plugins/sf_engine/ipv6_port.h.new> ../../dynamic-plugins/sf_engine/ipv6_port.h
copy ..\..\sfutil\sfhashfcn.c ..\..\dynamic-plugins\sf_engine\sfhashfcn.c.new
c:\cygwin\bin\sed -e "s/\#ifndef MODULUS_HASH/\#ifdef STATIC_HASH/" ../../dynamic-plugins/sf_engine/sfhashfcn.c.new> ../../dynamic-plugins/sf_engine/sfhashfcn.c
